apiVersion: v1
kind: Namespace
metadata:
  name: helloworld

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: helloworld
  name: dep-helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: dockercloud/hello-world
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  namespace: helloworld
  name: svc-helloworld
spec:
  selector:
    app: helloworld
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081