apiVersion: v1
kind: Namespace
metadata:
  name: minio

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: pvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: minio
  name: pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi