apiVersion: v1
kind: Namespace
metadata:
  name: pv-test-1
labels:
    backup: yes

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: pv-test-1
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  namespace: pv-test-1
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
